# Generated by Django 4.0.1 on 2022-02-06 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_image_alter_bid_id_alter_comment_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='name',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='listing',
        ),
    ]
