# Generated by Django 4.0.1 on 2022-02-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_name_bid_listing_rename_name_comment_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, upload_to='auctions/uploads'),
        ),
    ]
